### ISSUE TITLE
Blender package for OSX

### ISSUE THREAD

**Issue by morevnaproject** [0install/apps#40]
No OSX package for Blender.

**Comment by morevnaproject** [comment]
1. Added implementation for OSX to `blender.xml.template`:
```
      <implementation arch="MacOSX-x86_64" version="{version}" released="{released}" stability="{stability}" main="MacOS/Blender">
      <manifest-digest/>
      <archive href="https://download.blender.org/release/Blender{version-main}/blender-{version-full}-macOS.dmg" type="application/x-apple-diskimage" extract="Blender.app/Contents"/>
    </implementation>
```

2. Tried to add OSX package by running `0template` on Linux - got an error that `hdiutil` is not available.

3. Tried to run 0template on OSX - 0template fails to install. Reported to https://github.com/0install/0template/issues/17

**Comment by morevnaproject** [comment]
Ideally, it would be nice to have new versions of Blender for OSX also added to feed automatically, like it is currently [done](https://github.com/0install/apps/commit/2f3e3fb9e3a3913de6575906badaf97cf5124f1d) for Linux and Windows (thanks a lot for that!).

But Blender is shipped in `dmg` files, which cannot be unpacked on Linux.

So, implementing this will require to add OSX step to CI - https://github.com/0install/apps/blob/master/.github/workflows/update.yml

**Comment by bastianeicher** [comment]
I'll be happy to work on a MacOS step forthe CI pipeline as soon as we get 0install/0template#17 resolved. Might take a little trail and error though, since I don' have a Mac for local testing.

Thanks for the XML snippet for the Mac version of Blender. We'll need to change it slightly though, because 0install does not allow any slashes inside the `extract` value (only one directory dep). Perhaps like this:

```xml
<implementation arch="MacOSX-x86_64" version="{version}" released="{released}" stability="{stability}" main="Blender.app/Contents/MacOS/blender">
  <manifest-digest/>
  <archive href="https://download.blender.org/release/Blender{version-main}/blender-{version-full}-macOS.dmg" type="application/x-apple-diskimage" extract="Blender"/>
</implementation>
```

**Comment by morevnaproject** [comment]
> I'll be happy to work on a MacOS step forthe CI pipeline as soon as we get 0install/0template#17 resolved.

Thank you! As reported in https://github.com/0install/0template/issues/17#issuecomment-603845145, the problem seems not happens in CI.

**Comment by bastianeicher** [comment]
I've added a MacOS CI step in c7738d4 and MacOS implementations to the Blender feed in 2f5f638 (only 2.28 and 2.82a so far).

@morevnaproject Could you give `0install run https://apps.0install.net/gui/blender.xml` a try on MacOS and let me know if it works?

**Comment by morevnaproject** [comment]
I have tested, but it fails with  "incorrect manifest" error.
Tried 3 times - the error and digest are the same:

```
Mac-Admin:~ admin$ 0install run https://apps.0install.net/gui/blender.xml
Incorrect manifest -- archive is corrupted.                                     
Required digest: sha256new_R22JWU7PQ6KIIRZBIMDMJK43YKNI4XDWWOFTKMNV3OPSCNMEHFCA
Actual digest: sha256new_YHQGBGTOGZDODATUOBTJJWJAURC3DFHO2YMKRIADFMA6QVYSSQUQ
... downloading implementation https://apps.0install.net/gui/blender-macos.xml 2.82-1 (id=sha1new=b112dc1a29421931f9ca6aeab13a728269ae7b8a)
Mac-Admin:~ admin$ 0install run https://apps.0install.net/gui/blender.xml
Incorrect manifest -- archive is corrupted.                                     
Required digest: sha256new_R22JWU7PQ6KIIRZBIMDMJK43YKNI4XDWWOFTKMNV3OPSCNMEHFCA
Actual digest: sha256new_YHQGBGTOGZDODATUOBTJJWJAURC3DFHO2YMKRIADFMA6QVYSSQUQ
... downloading implementation https://apps.0install.net/gui/blender-macos.xml 2.82-1 (id=sha1new=b112dc1a29421931f9ca6aeab13a728269ae7b8a)
Mac-Admin:~ admin$ 0install run https://apps.0install.net/gui/blender.xml
Incorrect manifest -- archive is corrupted.                                                     
Required digest: sha256new_R22JWU7PQ6KIIRZBIMDMJK43YKNI4XDWWOFTKMNV3OPSCNMEHFCA
Actual digest: sha256new_YHQGBGTOGZDODATUOBTJJWJAURC3DFHO2YMKRIADFMA6QVYSSQUQ
... downloading implementation https://apps.0install.net/gui/blender-macos.xml 2.82-1 (id=sha1new=b112dc1a29421931f9ca6aeab13a728269ae7b8a)
Mac-Admin:~ admin$
```

![screenshot_007](https://user-images.githubusercontent.com/332868/79046803-2e4f0000-7c3d-11ea-90bf-2bbd0540d0c1.png)

**Comment by bastianeicher** [comment]
I've found the problem:

0template internally uses the Python version of Zero Install. This version has a bug that causes it to skip files and directories starting with a `.` when extracting `.dmg` files.

The normal version of 0install written in OCaml does not have this bug. Therefore the digests calculated by 0template did not match those calculated by `0install run`.

I have manually fixed the digests in the Blender MacOS feed in 3b9e44f, so `0install run https://apps.0install.net/gui/blender.xml` should work now.

I've also created a PR to fix the issue in the Python version of Zero Install so that 0template will work correctly for Blender on MacOS in the future: 0install/0install#151

**Comment by morevnaproject** [comment]
Thank you for the fix! I tested and it downloaded Blender successfully. I was unable to run it, because OSX 10.10 is too old for latest version of Blender, but the download process finished fine. ^__^

![screenshot_013](https://user-images.githubusercontent.com/332868/79254582-26969200-7eaf-11ea-9991-86eee873ff79.png)

**Comment by morevnaproject** [comment]
I think it can be closed now. Thanks again for adding OSX versions! ^__^

**Comment by bastianeicher** [comment]
You're welcome and thanks for testing. :)

By the way, Blender 2.79b runs on MacOS 10.9+, so you could try:

    0install run --version 2.79-2 https://apps.0install.net/gui/blender.xml
