### ISSUE TITLE
Missing versions for Blender package

### ISSUE THREAD

**Issue by morevnaproject** [0install/apps#42]
Just for record: a list for versions not included into Blender package feed: -

- [ ] 2.61
- [ ] 2.62
- [ ] 2.63
- [ ] 2.63a
- [ ] 2.64
- [ ] 2.64a
- [x] 2.65
- [x] 2.65a
- [x] 2.66a
- [x] 2.67a
- [x] 2.67b
- [x] 2.68a
- [x] 2.70a
- [x] 2.72a
- [x] 2.72b
- [x] 2.73a
- [x] 2.75
- [x] 2.75a
- [x] 2.76a
- [x] 2.76b
- [x] 2.80
- [x] 2.81
- [x] 2.81a

**Comment by bastianeicher** [comment]
I've added a number of previously missing versions in 03633bc.

**Comment by morevnaproject** [comment]
Awesome! Thank you so much!

I have noticed in https://github.com/0install/apps/commit/2f5f6387cf9f514b0b837402efdaa7bc8b6ea22e you separated Blender's .xml file.  I wonder what is the reason for that? This actually introduces some complications... ^__^"

**Comment by bastianeicher** [comment]
You can still use the feed https://apps.0install.net/gui/blender.xml. It contains the following references that tell 0install which additional feed to use, based on the operating system:

```xml
<feed arch="Linux-*" src="https://apps.0install.net/gui/blender-linux.xml"/>
<feed arch="MacOSX-*" src="https://apps.0install.net/gui/blender-macos.xml"/>
<feed arch="Windows-*" src="https://apps.0install.net/gui/blender-windows.xml"/>
```

Does this work for you?

Separating the feed into multiple parts keeps the file sizes that needs be downloaded a bit lower. It also makes it possible to run separate 0watch scripts on different operating systems in the CI job.

**Comment by morevnaproject** [comment]
> You can still use the feed https://apps.0install.net/gui/blender.xml

Ah, I see! Yes, as far as I can continue using a single xml file everything is good. ^__^

I will test it and get back soon.

**Comment by morevnaproject** [comment]
Referencing single XML works fine, thank you!^__^

I've got an digest error, reported in https://github.com/0install/apps/issues/40#issuecomment-612436403.
