### ISSUE TITLE
please add gojq

### ISSUE THREAD

**Issue by pkoppstein** [0install/apps#433]
gojq recently reached Version v0.12.5, so now would be a great time to have it supported by 0install:

https://github.com/itchyny/gojq

**Comment by bastianeicher** [comment]
Added feed in 7ecc78bea6113fe3ad32ccb89f3e0268a12e990e.

gojq can now be run with:

    0install run https://apps.0install.net/utils/gojq.xml

**Comment by pkoppstein** [comment]
@bastianeicher - Thank you!
