### ISSUE TITLE
Problem with minikube feed

### ISSUE THREAD

**Issue by afbjorklund** [0install/apps#69]
Hi @bastianeicher, I seem to be having some issues with the minikube feed:

```console
$ 0install -c run https://apps.0install.net/kubernetes/minikube.xml
Incorrect manifest -- archive is corrupted.                                                                    
Required digest: sha256new_COUKLDJ3K547BUITQTMI3KIXICLFELV5OAPPAURHJMIRIP6V2SWA
Actual digest: sha256new_IN5EGYYHA4Y7MG2JHVVIHL6ZUHVXMQSZHQ54SQHY2KPZ2N5LGNDQ
... downloading implementation https://apps.0install.net/kubernetes/minikube.xml 1.9.2 (id=sha1new=0b3b3f0bd8fef38e83e71b08d7e64e39fad6e31d)
```

I'm wondering if it could be related to the timestamps not being preserved OK ?

 https://storage.googleapis.com/minikube/releases/v1.9.2/minikube-linux-amd64

`last-modified: Sat, 04 Apr 2020 21:03:55 GMT`

It would be great if this could be fixed!

https://github.com/kubernetes/minikube/issues/7978

----

PS. We also have a logo, that could be used as an icon ? (might have to be resized)

https://github.com/kubernetes/minikube/blob/master/images/logo/minikube-logo.png

**Comment by bastianeicher** [comment]
Hi @afbjorklund,

the Minikube feed uses a `<file>` tag to download the binary (no archive to extract). 0install always sets the timestamp for such files to `0` in unix time.

The feed also uses the attribute `executable="true"` to effectively `chmod +x` the downloaded binary. Support for this was added in 0install 2.13. Perhaps you are running an older version of 0install? That would lead to the executable bit missing and thereby invalidate the digest.

You could give this a try to bootstrap the latest 0install version:

	0install run http://0install.net/tools/0install.xml run https://apps.0install.net/kubernetes/minikube.xml

Thanks for the icon link. I've added it in e4f011e.

**Comment by afbjorklund** [comment]
> You could give this a try to bootstrap the latest 0install version:

Thanks, that works much better! I was using 0install  `2.12.3`

It works out of the box in Ubuntu 20.04, but **not** in the older...

https://packages.ubuntu.com/search?keywords=0install-core

I'm thinking that if I add the _tarballs_ and some icons, it would work ?

And also be a smaller download for the user, than the current ones.

Like ~~https://github.com/kubernetes/minikube/issues/4699~~

> Thanks for the icon link.

It's not perfect, it is too big and is missing the transparency...

Will add one that is more suitable for a desktop icon context:

![icon](https://user-images.githubusercontent.com/10364051/80912318-73e28280-8d3c-11ea-9767-26ae8dc4dae4.png)

256x256 (also .svg)

**Comment by bastianeicher** [comment]
Tarball releases for Minikube would be great!

I've added the new icon to the feed in ced3a00.

**Comment by afbjorklund** [comment]
Starting with minikube 1.10.0, there are now tarballs uploaded as well:

https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-linux-amd64.tar.gz

**Comment by bastianeicher** [comment]
@afbjorklund Thanks!

I've updated the minikube feed to use the tarballs in c79b9f83baf8450bbea5c6f480989726a2cd8726.
